import { isAutoGenerated } from '../prompts/strategyConstants';

/** 將範本 markdown 包裝為 prompt 注入文字 */
export const templateToPrompt = (contentMd: string): string => {
  return `\n═══ 律師指定的書狀範本 ═══
以下是律師為本案指定的範本，請依照此範本的格式、結構與慣例撰寫書狀。
其他未指定的事項仍依上方預設慣例。
如有本範本未涵蓋的重要事項，得在範本結構之後補充新增段落。

${contentMd}`;
};

// ── Template Section Parser ──

export type SectionType = 'fixed' | 'ai_planned' | 'system_generated';

export interface TemplateSection {
  name: string;
  type: SectionType;
}

// 大寫中文數字，用於匹配段落標題行首
const CJK_NUMERALS = '壹貳參肆伍陸柒捌玖拾';
const SECTION_HEADING_RE = new RegExp(`^(?:##\\s*)?([${CJK_NUMERALS}]+、[^\\n]+)$`);

// 固定內容段落（已有完整法律文字，不需 AI 規劃）
const FIXED_KEYWORDS = ['訴之聲明', '答辯聲明', '上訴聲明', '執行名義', '請求金額', '聲請執行標的'];

const classifySection = (name: string): SectionType => {
  if (isAutoGenerated(name)) return 'system_generated';
  if (FIXED_KEYWORDS.some((kw) => name.includes(kw))) return 'fixed';
  return 'ai_planned';
};

/** 從 template markdown 解析段落清單，分類為 fixed / ai_planned / system_generated */
export const extractSections = (templateMd: string): TemplateSection[] => {
  const sections: TemplateSection[] = [];
  const lines = templateMd.split('\n');

  for (const line of lines) {
    const trimmed = line.trim();
    // 匹配 "## 壹、..." 或直接 "壹、..." 開頭的行
    const match = trimmed.match(SECTION_HEADING_RE);
    if (match) {
      const name = match[1].trim();
      sections.push({ name, type: classifySection(name) });
    }
  }

  return sections;
};

const TYPE_LABELS: Record<SectionType, string> = {
  fixed: '固定內容，不需 AI 規劃',
  ai_planned: '需要 AI 規劃',
  system_generated: '系統自動產生，不需 AI 規劃',
};

/** 將段落清單轉為 prompt 注入文字 */
export const sectionsToPrompt = (sections: TemplateSection[]): string => {
  const lines = sections.map((s, i) => `${i + 1}. ${s.name} → ${TYPE_LABELS[s.type]}`);

  return `\n═══ 本案書狀段落結構 ═══
依據範本，本書狀包含以下段落（按順序）：

${lines.join('\n')}

你的 sections[] 只需為標記「需要 AI 規劃」的段落產出 section 計畫。
section 名稱必須完全使用上面列出的段落名稱（含中文編號）。`;
};
