// ── Template Renderer (Flash Lite) ──
// Renders template header, fillable sections, and footer by filling in case data.
// Uses Gemini Flash Lite for context-aware placeholder replacement.

import { callOpenRouterText, type AIEnv } from '../aiClient';
import type { ClientRole } from '../../../shared/caseConstants';
import { isAutoGenerated } from '../prompts/strategyConstants';
import { formatDamageAmount, type DamageItem } from './types';

export interface CaseDataForRender {
  plaintiff: string | null;
  defendant: string | null;
  caseNumber: string | null;
  court: string | null;
  division: string | null;
  clientRole: ClientRole | null;
  damageItems: DamageItem[];
}

export interface RenderedTemplate {
  header: string | null;
  sections: Array<{ heading: string; content: string }>;
  footer: string | null;
}

/** Parse template into header, body sections, and footer */
export const parseTemplate = (
  contentMd: string,
): {
  header: string;
  sections: Array<{ heading: string; body: string }>;
  footer: string;
} => {
  const lines = contentMd.split('\n');
  let header = '';
  const sections: Array<{ heading: string; body: string }> = [];
  let footer = '';
  let inFooter = false;
  let currentHeading = '';
  let currentBody: string[] = [];

  for (const line of lines) {
    if (line.startsWith('---') && sections.length > 0) {
      if (currentHeading) {
        sections.push({ heading: currentHeading, body: currentBody.join('\n').trim() });
        currentHeading = '';
        currentBody = [];
      }
      inFooter = true;
      continue;
    }

    if (inFooter) {
      footer += line + '\n';
      continue;
    }

    if (line.startsWith('## ')) {
      if (currentHeading) {
        sections.push({ heading: currentHeading, body: currentBody.join('\n').trim() });
      } else if (currentBody.length > 0) {
        header = currentBody.join('\n').trim();
      }
      currentHeading = line.replace(/^## /, '').trim();
      currentBody = [];
      continue;
    }

    currentBody.push(line);
  }

  if (currentHeading) {
    sections.push({ heading: currentHeading, body: currentBody.join('\n').trim() });
  } else if (!header && currentBody.length > 0) {
    header = currentBody.join('\n').trim();
  }

  return { header, sections, footer: footer.trim() };
};

// ── Section classification ──

/** Section body has ○○ or 【待填 placeholders → needs Flash Lite rendering */
const isFillable = (body: string): boolean => body.includes('○○') || body.includes('【待填');

// ── Flash Lite rendering ──

const RENDER_SYSTEM_PROMPT = `你是書狀格式填寫助手。將範本中的 ○○○ 和【待填】佔位符替換為案件資料。

嚴格規則：
- 只替換佔位符（○○○ 和【待填：xxx】），不要新增、刪除或重新排列任何文字
- 輸出必須與輸入行數相同，只有佔位符的值改變
- 有資料時直接替換（例如 ○○○ → 林小明）
- 沒有資料時將 ○○○ 改為【待填：描述】格式
- 法院名稱格式：臺灣○○地方法院（例如 court=臺北 → 臺灣臺北地方法院）
- 金額使用千分位格式（例如 583200 → 583,200）
- 禁止新增任何段落、標題、或結構
- 輸出純文字，不要加 markdown 標記`;

const buildCaseDataBlock = (caseData: CaseDataForRender): string => {
  const items = caseData.damageItems;
  const damagesTotal = items.length > 0 ? items.reduce((sum, d) => sum + d.amount, 0) : null;
  const damageLines =
    items.length > 0 ? items.map((d) => `  ${formatDamageAmount(d)}`).join('\n') : '';

  return `案件資料：
原告：${caseData.plaintiff || '（無）'}
被告：${caseData.defendant || '（無）'}
案號：${caseData.caseNumber || '（無）'}
法院：${caseData.court || '（無）'}
庭別：${caseData.division || '（無）'}
當事人立場：${caseData.clientRole || '未指定'}
請求金額合計：${damagesTotal ? `新臺幣${damagesTotal.toLocaleString()}元` : '（無）'}${damageLines ? `\n請求金額明細：\n${damageLines}` : ''}`;
};

/** Render header, fillable sections, and footer with case data via Flash Lite */
export const renderTemplate = async (
  aiEnv: AIEnv,
  templateContent: string,
  caseData: CaseDataForRender,
  signal?: AbortSignal,
): Promise<RenderedTemplate> => {
  const parsed = parseTemplate(templateContent);
  const caseDataBlock = buildCaseDataBlock(caseData);

  const renderPart = async (part: string): Promise<string> => {
    const userMessage = `${caseDataBlock}

以下是需要填入的範本片段（只有這些文字，不要新增任何內容）：

${part}`;
    const result = await callOpenRouterText(aiEnv, RENDER_SYSTEM_PROMPT, userMessage, {
      maxTokens: 1024,
      signal,
    });
    return result.content.trim();
  };

  // Classify sections
  const fillableSections = parsed.sections.filter(
    (s) => isFillable(s.body) && !isAutoGenerated(s.heading),
  );

  // Render header, fillable sections, and footer in parallel
  const results = await Promise.all([
    parsed.header.trim() ? renderPart(parsed.header) : Promise.resolve(null),
    ...fillableSections.map((s) => renderPart(s.body)),
    parsed.footer.trim() ? renderPart(parsed.footer) : Promise.resolve(null),
  ]);

  const header = results[0];
  const sectionResults = results.slice(1, 1 + fillableSections.length) as string[];
  const footer = results[results.length - 1];

  const sections = fillableSections.map((s, i) => ({
    heading: s.heading,
    content: sectionResults[i],
  }));

  return { header, sections, footer };
};
