// ── Shared constants for reasoning strategy prompts & pipeline ──
// Used by reasoningStrategyPrompt.ts (Reasoning 階段),
// reasoningStrategyStep.ts (Structuring 階段), and test scripts.

// ── Pipeline Constants ──

export const MAX_ROUNDS = 6;
export const MAX_SEARCHES = 6;
export const SOFT_TIMEOUT_MS = 25000;
export const MAX_TOKENS = 8192;
export const JSON_OUTPUT_MAX_TOKENS = 32768;
export const CLAUDE_MODEL = 'claude-haiku-4-5-20251001';
export const TOOL_RESULT_MAX_CHARS = 200;

// ── System-managed sections (不由 AI 撰寫，由程式產出) ──

export const AUTO_HEADINGS = ['證據方法', '證據'];

export const isAutoGenerated = (heading: string): boolean =>
  AUTO_HEADINGS.some((h) => heading.includes(h));

// 通用撰寫原則（所有書狀都適用，不含具體結構）
export const WRITING_CONVENTIONS = `═══ 書狀撰寫慣例 ═══

段落編號使用中文數字：壹、貳、參…，子段落使用一、二、三…。
每份書狀應包含前言段落與結論段落。
若有提供書狀範本，依照範本的段落結構與編號順序。
已有完整法律文字的段落（如訴之聲明）不需要 AI 規劃，只為需要撰寫的段落產出 section 計畫。`;

export const CLAIMS_RULES = `═══ Claims 規則 ═══

### Claims 提取
- ours：我方主張（從案件事實、爭點中提取），必須有 assigned_section
- theirs：對方主張（從對方書狀、答辯中提取），assigned_section 為 null
- 對方每個主要主張都需要有 ours claim 來回應

### Claim 類型（claim_type）
- primary：主要主張（雙方的核心法律主張）
- rebuttal：反駁（直接回應對方某個 claim）
- supporting：輔助（支持同段落的主要主張）

### 攻防配對
- dispute_id：連結到對應爭點的真實 ID（必須使用[爭點清單]中方括號內的 ID，不要自己編造）
- responds_to：攻防配對，填入所回應的 claim ID
  - rebuttal claim 必須有 responds_to（指向被反駁的 claim）
  - supporting claim 必須有 responds_to（指向它輔助的 primary claim）
  - primary claim 的 responds_to 為 null
- 每個 theirs 的 primary/rebuttal claim 應有對應的 ours rebuttal claim 來回應`;

export const SECTION_RULES = `═══ 段落規則 ═══

- 每個段落需要有完整的論證框架（大前提—小前提—結論）
- section：大段名稱（依範本結構編號，如「貳、前言」「參、事實及理由」「伍、結論」）
- subsection：子段標題（如「一、侵權行為之成立」「二、醫療費用」）。前言和結論為 null，其餘每個段落必須填寫 subsection，格式為「一、描述性標題」「二、描述性標題」，依序編號
- legal_basis：引用的法條 ID（必須是已查到全文的法條，且必須在 relevant_law_ids 中）
- fact_application：事實如何涵攝到法律要件
- conclusion：本段小結論
- dispute_id：連結到對應爭點的真實 ID（前言和結論為 null，其餘段落必須填入[爭點清單]中的 ID）
- relevant_file_ids：列出本段撰寫時需要引用的來源檔案 ID（重要！確保每個論述段都有對應的來源檔案，否則 Writer 無法產生引用標記）
- relevant_law_ids：列出本段需要引用的法條 ID
- legal_reasoning：本段的法律推理摘要（不超過 500 字），包含：
  - 為什麼用這個請求權基礎（如有比較則簡述理由）
  - 構成要件如何對應到事實
  - 預判對方可能的攻擊角度及我方回應
- 不要規劃「證據方法」段落，證據方法由系統自動從證據清單產生`;

export const STRATEGY_JSON_SCHEMA = `═══ JSON 格式 ═══

段落 ID 命名規則：前言 section_1、第一個子段落 section_2_1、第二個子段落 section_2_2、損害賠償 section_3（若有）、結論 section_last。子段落 ID 格式為 section_{大段號}_{子段號}。

重要：前言和結論不需要 subsection，其餘每個段落必須填寫 subsection（格式：一、描述性標題）。
重要：section 名稱的中文編號必須依照範本結構（若有範本則依範本段落順序）。

以下為起訴狀範例：

{
  "claims": [
    {
      "id": "their_claim_dispute1",
      "side": "theirs",
      "claim_type": "primary",
      "statement": "對方主張的描述",
      "assigned_section": null,
      "dispute_id": "（填入[爭點清單]中的真實 ID）",
      "responds_to": null
    },
    {
      "id": "our_claim_dispute1_primary",
      "side": "ours",
      "claim_type": "primary",
      "statement": "我方主要主張",
      "assigned_section": "section_2_1",
      "dispute_id": "（填入[爭點清單]中的真實 ID）",
      "responds_to": null
    },
    {
      "id": "our_claim_dispute1_rebuttal1",
      "side": "ours",
      "claim_type": "rebuttal",
      "statement": "反駁對方主張的一句話描述",
      "assigned_section": "section_2_1",
      "dispute_id": "（填入[爭點清單]中的真實 ID）",
      "responds_to": "their_claim_dispute1"
    }
  ],
  "sections": [
    {
      "id": "section_1",
      "section": "貳、前言",
      "subsection": null,
      "dispute_id": null,
      "argumentation": {
        "legal_basis": [],
        "fact_application": "簡述案件背景",
        "conclusion": "本狀針對被告答辯逐一反駁"
      },
      "claims": ["our_claim_overview"],
      "relevant_file_ids": [],
      "relevant_law_ids": [],
      "legal_reasoning": ""
    },
    {
      "id": "section_2_1",
      "section": "參、事實及理由",
      "subsection": "一、侵權行為之成立",
      "dispute_id": "（填入[爭點清單]中的真實 ID）",
      "argumentation": {
        "legal_basis": ["B0000001-184"],
        "fact_application": "事實涵攝描述",
        "conclusion": "本段結論"
      },
      "claims": ["our_claim_dispute1_primary", "our_claim_dispute1_rebuttal1"],
      "relevant_file_ids": ["file_1"],
      "relevant_law_ids": ["B0000001-184"],
      "facts_to_use": [
        {
          "fact_id": "fact_1",
          "assertion_type": "爭執",
          "usage": "作為過失要件的核心事實論據"
        }
      ],
      "legal_reasoning": "以 184-1前段為主要請求權基礎..."
    },
    {
      "id": "section_2_2",
      "section": "參、事實及理由",
      "subsection": "二、醫療費用之請求",
      "dispute_id": "（填入[爭點清單]中的真實 ID）",
      "argumentation": {
        "legal_basis": ["B0000001-193"],
        "fact_application": "醫療費用事實涵攝",
        "conclusion": "醫療費用應予認定"
      },
      "claims": ["our_claim_dispute2_primary"],
      "relevant_file_ids": ["file_2"],
      "relevant_law_ids": ["B0000001-193"],
      "legal_reasoning": "以民法§193為請求權基礎..."
    },
    {
      "id": "section_2_3",
      "section": "參、事實及理由",
      "subsection": "三、精神慰撫金之請求",
      "dispute_id": "（填入[爭點清單]中的真實 ID）",
      "argumentation": {
        "legal_basis": ["B0000001-195"],
        "fact_application": "精神損害事實涵攝",
        "conclusion": "慰撫金請求合理"
      },
      "claims": ["our_claim_dispute3_primary"],
      "relevant_file_ids": ["file_1"],
      "relevant_law_ids": ["B0000001-195"],
      "legal_reasoning": "以民法§195為請求權基礎..."
    },
    {
      "id": "section_last",
      "section": "伍、結論",
      "subsection": null,
      "dispute_id": null,
      "argumentation": {
        "legal_basis": [],
        "fact_application": "",
        "conclusion": "綜上所述，請求鈞院判決如訴之聲明"
      },
      "claims": [],
      "relevant_file_ids": [],
      "relevant_law_ids": [],
      "legal_reasoning": ""
    }
  ]
}`;
